import keyboard
import time

'''
compra_ora = keyboard.press("D")
indietro = keyboard.press("Q")
aumenta_prezzo_minimo = keyboard.press("A")
diminuisci_prezzo_minimo = keyboard.press("B")
cerca = keyboard.press("S")
'''

tempo_corto = input("Quanti secondi ci devono essere tra un'azione e l'altra?\n")
tempo_lungo = input("Quanti secondi ci devono essere di attesa ogni 5 ricerche?\n")

time.sleep(10)
while True:
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("a")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("b")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("a")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("b")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("a")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("b")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("a")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("b")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("a")
    time.sleep(float(tempo_corto))
    keyboard.press("s")
    time.sleep(0.3)
    keyboard.press("d")
    time.sleep(float(tempo_corto))
    keyboard.press("q")
    time.sleep(float(tempo_corto))
    keyboard.press("b")
    time.sleep(float(tempo_lungo))